# Use the README file as a reference to customize settings.

SubCategory:
  fields:
    default: name, image, category_id
    form: name, image, category_id
  relationships: products
  application: Application
