# Use the README file as a reference to customize settings.

User:
  fields:
    default: name, username, email, about, encrypted_password, city, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, stripe_customer_id, deleted, confirmation_token, confirmed_at, confirmation_sent_at, unconfirmed_email, failed_attempts, unlock_token, locked_at, authentication_token
    form: name, username, email, about, encrypted_password, city, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, stripe_customer_id, deleted, confirmation_token, confirmed_at, confirmation_sent_at, unconfirmed_email, failed_attempts, unlock_token, locked_at, authentication_token
  relationships: 
  application: Application
